name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet 
        uses: actions/setup-dotnet@v3

      - name: Build
        run: dotnet build Myservice.sln
      
      - name: publish
        run: dotnet publish -c Release Myservice/Myservice.csproj
      
      - name: release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          release_name: v1.0.4
          tag_name: v1.0.4
          body: |
            Changes in this Release
            - First Change
            - Second Change
            
      - uses: vimtor/action-zip@v1.2
        with:
          files: Myservice/bin/Debug/net8.0/
          dest: result.zip
      
      - name: upload  artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./result.zip
          asset_name: result.zip
          asset_content_type: application/gzip


